-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 22:15:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RH` DEFAULT CHARACTER SET utf8 ;
USE `RH` ;

-- -----------------------------------------------------
-- Table `RH`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RH`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(5,2) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into funcionario(idFuncionario,nome,salario,email,telefone)values
(1,"max",1000.00,"maxmarouane@gmail.com",1194763706),
(2,"petit",2000.00,"petitmaro@gmail.com",1199999999),
(3,"lor",2500.00,"lord@gmail.com",1299999999),
(4,"cool",1500.20,"cool@gmail.com",1278945612),
(5,"sthene",4500.02,"msthene@gamil.com",1123154678);

select * from funcionario;
select * from funcionario where salario>2000;
select * from funcionario where salario<2000;
update funcionario set salario = 8000.00 where idFuncionario > 2;
alter table funcionario modify salario decimal(6,2);
